spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    password: root
    username: root
management:
  metrics:
    tags:
      used: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, metric
logging:
  level:
    ru.etu.stud.java.synchronous.tools: DEBUG