spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    password: root
    username: root
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  datadog:
    metrics:
      export:
        uri: https://api.datadoghq.eu
        api-key: ${DATADOG_TOKEN}
        step: 10s
logging:
  level:
    ru.etu.stud.java.synchronous.tools: DEBUG